### PR TITLE
Improves contrast and resolves #76

### LINKED ISSUE #76: Improve contrast on ROR site
Sharing a handful of contrast issues:

* Support link in top right and "search page" below the search bar: https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=53BAA1
* Search icon in the search bar is a very light grey on white
* On https://ror.org/about/, the navigation links are pretty much the inverse of the support link, with grey instead of white: https://webaim.org/resources/contrastchecker/?fcolor=53BAA1&bcolor=EFEFEF
* On the search results and the blog, the grey buttons with white text are a bit low: https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=888888

For the most part it's very clear! I like WebAIM's WAVE tool as a quick way to confirm contrast: https://wave.webaim.org/

### PR DESCRIPTION
**Pull request by amandafrench**
Resolves the 2 remaining issues of 4 in #76 by changing link text on external link to black and using ROR theme dark gray for gray buttons on blog.

### CODE REVIEW

**Comment by amandafrench** [comment]
external-link-and-button-contrast

**Comment by amandafrench** [comment]
If these changes look good I can make them on ror-app as well

**Comment by amandafrench** [comment]
This is what the dark gray button would look like on ror-app
search-app-button-contrast

**Comment by lizkrznarich** [comment]
@amandafrench ror-app shares its base css files with ror-site, so let's just merge this to dev and check that ror-app has the changes.

**Review by lizkrznarich — APPROVED** [review]

**Pull request merged**
