### PR TITLE
Be a bit more specific about the structure of the identifier

### PR DESCRIPTION
**Pull request by jdvorak001**
I'm suggesting to:
- be more specific about the classes and the case of the characters
- mention also 'u' is excluded
- reference the specific checksum algorithm

### CODE REVIEW

**Comment by jdvorak001** [comment]
Hello, a bit about the motivation of this pull request. 
We are trying to define a datatype for the ROR identifiers in the context of the [CERIF Refactoring Project](https://www.eurocris.org/cerif-refactoring-project-introduction). In order to constrain the identifier space as tightly as possible we:
- built a regular expression (`https://ror\.org/0[0-9a-hjkmnp-tv-z]{6}(0[2-9]|[1-8][0-9]|9[0-8])`);
- specify how the checksums should be validated.
The original description of the structure of the identifier was useful, but I noticed it took a bit of further research to get all the details. So I'm suggesting the additional info perhaps be incorporated in the ROR page.

**Comment by amandafrench** [comment]
@jdvorak001 Hi Jim -- thought you might like to know that we did recently add some information about the pattern of the ROR identifier to our technical documentation, though not to the ROR website itself. See https://ror.readme.io/docs/ror-identifier-pattern 

How does that look? Is the link to the [Crockford Base 32 encoding page](https://www.crockford.com/base32.html) enough for the checksum validation information you're looking for?

**Comment by jdvorak001** [comment]
@amandafrench Amanda, that looks like a step in the good direction, thanks. You are correct that the checksum algorithm is not the original one form the Crockford Base 32 encoding page (modulo 37), it's a different one: modulo 97-10 from [ISO-7064](https://www.iso.org/standard/31531.html). By interpreting the info from https://ror.org/facts/ we compiled an even more specific regexp, see our [ROR_ID datatype description page](https://github.com/EuroCRIS/CERIF-Core/blob/main/datatypes/ROR_ID.md). I took a ROR dump and verified both the regexp and the checksum for all ROR IDs there were some time back in 2021.

**Comment by amandafrench** [comment]
Great, thanks! Appreciate the input. We've updated that [page in the documentation](https://ror.readme.io/docs/ror-identifier-pattern) with a link to the code in the ROR API that actually generates the ROR ID and describes the checksum calculation. @mariagould, can you close the pull request?

**Comment by jdvorak001** [comment]
Looks good to me. I'd just suggest to specifically name the "modulo 97-10" algorithm as the standard defines several of them. 

Also, our regexp more closely represents the fact that the check digits will always be between 02 and 98 (inclusive), so you might want to include it as the most constraining one.

**Comment by lizkrznarich** [comment]
@jdvorak001 We'd prefer to leave the link to the code rather than explain the checksum in documentation, as the code is quite clear for those who need that level of detail. Also, since we are currently revising our information site and moving all tech docs to the support site ror.readme.io, I'm going to close this PR. Information about the ROR ID structure will be maintained in https://ror.readme.io/docs/ror-identifier-pattern going forward.

**Pull request closed without merging**
