### PR TITLE
Add mastodon to social footer

### PR DESCRIPTION
**Pull request by amandafrench**
Adds Mastodon image and verify link to footer. Please note @lizkrznarich that this would need to be replicated in ror-app.  Note too that it is a hack because I've added the Mastodon icon as a PNG file instead of using Font Awesome because the Mastodon icon isn't in version 4 of Font Awesome, which is what the ROR site currently uses. Issue #86 requests an update to the version of Font Awesome.

### CODE REVIEW

**Comment by amandafrench** [comment]
Mastodon icon is in FA starting with v 5.011 https://fontawesome.com/icons/mastodon?s=solid&f=brands

**Review by mariagould — APPROVED** [review]
Looks good!

**Comment by lizkrznarich** [comment]
This is good for now, but I'd suggest we just upgrade to the latest Fontawesome version. Icon names are formatted differently in v5+, but we don't have a huge number of icons in use and there's even a shim for v4 compatibility if we don't  feel like updating the existing icons https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4 . I can do this, since I'm fiddling around with ror-app atm anway.

**Comment by amandafrench** [comment]
That would be great, thanks!

**Pull request closed without merging**
